name: CI

on:
  push:
    tags:
      - v*
    branches:
      - trunk
  pull_request:

jobs:
  # Code linting
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Lint code
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6.2

  # Unit tests on Linux
  unit-tests-linux:
    name: Unit tests on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25.4"

      - name: Check out code
        uses: actions/checkout@v5

      - name: Run unit tests
        run: make test

  # Unit tests on macOS
  unit-tests-macos:
    name: Unit tests on macOS
    runs-on: macos-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25.4"

      - name: Check out code
        uses: actions/checkout@v5

      - name: Run unit tests
        run: make test

  # Unit tests on Windows
  unit-tests-windows:
    name: Unit tests on Windows
    runs-on: windows-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25.4"

      - name: Check out code
        uses: actions/checkout@v5

      - name: Run unit tests
        run: make test
